# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches: main

jobs:
  # This workflow contains a single job called "greet"
  greet:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
      
    steps:
    - name: Configura o Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      
    # Runs a single command using the runners shell
    - name: Install pyintaller and generator binary
      run: |
           pip install pyinstaller
           pyinstaller --onefile ./vapix.py
